need to close iterators in newer badger version
was getting this:

--- FAIL: TestNew (0.00s)
panic: Unclosed iterator at time of Txn.Discard. [recovered]
	panic: Unclosed iterator at time of Txn.Discard.

goroutine 18 [running]:
testing.tRunner.func1(0xc4201e60f0)

/nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/testing/testing.go:742
+0x29d
panic(0x9a4300, 0xb1b6a0)

/nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/runtime/panic.go:502
+0x229
github.com/dgraph-io/badger.(*Txn).Discard(0xc4201b4120)

/home/cryptix/go/src/github.com/dgraph-io/badger/transaction.go:428
+0xdc
github.com/dgraph-io/badger.(*DB).View(0xc420204000, 0xc420091ea0, 0x0,
0x0)

/home/cryptix/go/src/github.com/dgraph-io/badger/transaction.go:567
+0x95
go.cryptoscope.co/sbot/repo.(*repo).KnownFeeds(0xc420182320, 0x0, 0x0,
0xc420091f88)
	/home/cryptix/go/src/go.cryptoscope.co/sbot/repo/repo.go:89
+0x5c
go.cryptoscope.co/sbot/repo.TestNew(0xc4201e60f0)
	/home/cryptix/go/src/go.cryptoscope.co/sbot/repo/repo_test.go:21
+0x16c
testing.tRunner(0xc4201e60f0, 0xac33a0)

/nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/testing/testing.go:777
+0xd0
created by testing.(*T).Run

/nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/testing/testing.go:824
+0x2e0
FAIL	go.cryptoscope.co/sbot/repo	0.009s